BeforeAll {
    $RepoRoot = (Resolve-Path "$PSScriptRoot/../..").Path
    $ScriptPath = Join-Path $RepoRoot "bootstrap/windows/Install-ToPath.ps1"
}

Describe "Windows Install-ToPath bootstrap" {
    It "parses and exposes help" {
        { [scriptblock]::Create((Get-Content -Raw $ScriptPath)) } | Should -Not -Throw
        $output = & $ScriptPath -Help 2>&1 | Out-String
        $output | Should -Match "Инсталира scripts-toolbox"
    }

    It "dry-run lists marked PowerShell entrypoints without creating target" {
        $TempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ([System.Guid]::NewGuid().ToString())
        $Source = Join-Path $TempRoot "repo"
        $ToolDir = Join-Path $Source "tools/demo/powershell"
        $Packages = Join-Path $Source "packages"
        $Target = Join-Path $TempRoot "bin"
        New-Item -ItemType Directory -Path $ToolDir -Force | Out-Null
        New-Item -ItemType Directory -Path $Packages -Force | Out-Null
        try {
            @"
#!/usr/bin/env pwsh
# scripts-toolbox: entrypoint
# scripts-toolbox: command=demo-ps
Write-Output 'demo'
"@ | Set-Content -Path (Join-Path $ToolDir "demo.ps1") -Encoding UTF8

            $output = & $ScriptPath -Source $Source -Target $Target -PowerShell -DryRun 6>&1 2>&1 | Out-String
            $output | Should -Match "demo-ps.cmd"
            Test-Path $Target | Should -BeFalse
        }
        finally {
            Remove-Item -Recurse -Force $TempRoot -ErrorAction SilentlyContinue
        }
    }

    It "creates cmd wrappers for marked scripts" {
        $TempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ([System.Guid]::NewGuid().ToString())
        $Source = Join-Path $TempRoot "repo"
        $ToolDir = Join-Path $Source "tools/demo/powershell"
        $Packages = Join-Path $Source "packages"
        $Target = Join-Path $TempRoot "bin"
        New-Item -ItemType Directory -Path $ToolDir -Force | Out-Null
        New-Item -ItemType Directory -Path $Packages -Force | Out-Null
        try {
            @"
#!/usr/bin/env pwsh
# scripts-toolbox: entrypoint
# scripts-toolbox: command=demo-ps
Write-Output 'demo'
"@ | Set-Content -Path (Join-Path $ToolDir "demo.ps1") -Encoding UTF8

            & $ScriptPath -Source $Source -Target $Target -PowerShell
            $wrapper = Join-Path $Target "demo-ps.cmd"
            Test-Path $wrapper | Should -BeTrue
            (Get-Content -Raw $wrapper) | Should -Match "generated by scripts-toolbox"
            (Get-Content -Raw $wrapper) | Should -Match "demo.ps1"
        }
        finally {
            Remove-Item -Recurse -Force $TempRoot -ErrorAction SilentlyContinue
        }
    }
}
