#!/usr/bin/env bash
set -euo pipefail

# Repo-aware installer за команди от scripts-toolbox.
# Създава symlink-и или леки wrapper-и в target директория като ~/bin,
# без да добавя много source директории към PATH.

TOOLBOX_ENTRYPOINT_MARKER="scripts-toolbox: entrypoint"
TOOLBOX_NO_PATH_MARKER="scripts-toolbox: no-path"
WRAPPER_MARKER="# generated by add-scripts-to-path.sh"

SOURCE_DIR=""
TARGET_DIR="$HOME/bin"
DRYRUN=0
CLEAN=0
INCLUDE_UNMARKED=0
INCLUDE_PY=0
INCLUDE_SH=1
INCLUDE_PS1=0
INCLUDE_BAT=0
INCLUDE_ALL=0

show_help() {
cat <<'HELP'
Употреба: add-scripts-to-path.sh [опции] /път/към/scripts-root

Създава symlink-и или леки wrapper-и в target директория, така че скриптовете
да са достъпни като команди, без да се добавя цялото repo дърво към PATH.

Поведение по подразбиране:
  - включва Bash скриптове
  - включва само файлове с marker: scripts-toolbox: entrypoint
  - пропуска файлове с marker: scripts-toolbox: no-path
  - пропуска bootstrap, packages, tests, docs, samples, examples, archives, venvs и caches

Опции:
  -h, --help              Показва тази помощ
  -n, --dry-run           Показва действията, без да променя файлове
  -c, --clean             Премахва счупени symlink-и и остарели managed wrapper-и
  -t, --target DIR        Target директория за команди (по подразбиране: ~/bin)
  -s, --source DIR        Source repo/директория; алтернатива на позиционния аргумент
  -p, --python            Включва .py скриптове
  -b, --bash              Включва .sh скриптове (включено по подразбиране)
  -w, --powershell        Включва .ps1 скриптове
  -B, --bat               Включва .bat/.cmd скриптове
  -a, --all               Включва Bash, Python, PowerShell и Batch/CMD
  -u, --include-unmarked  Включва и shebang скриптове без entrypoint marker

Markers:
  scripts-toolbox: entrypoint   публикува файла като команда
  scripts-toolbox: no-path      никога не публикува файла като команда
  no-venv                       за Python: wrapper със system python вместо venv wrapper

Примери:
  add-scripts-to-path.sh -a ~/scripts
  add-scripts-to-path.sh -p -b -t ~/.local/bin ~/scripts
  add-scripts-to-path.sh -a -u -n ~/scripts
  add-scripts-to-path.sh -c -t ~/bin
HELP
}

fail() {
    echo "Грешка: $*" >&2
    exit 1
}

has_command() {
    command -v "$1" >/dev/null 2>&1
}

realpath_safe() {
    if has_command realpath; then
        realpath -m "$1"
    else
        python3 -c 'import os,sys; print(os.path.abspath(sys.argv[1]))' "$1"
    fi
}

is_ignored_path() {
    local file="$1"
    case "$file" in
        */.git/*|*/.idea/*|*/.vscode/*|*/__pycache__/*|*/.pytest_cache/*) return 0 ;;
        */.venv/*|*/venv/*|*/env/*|*/node_modules/*) return 0 ;;
        */bootstrap/*|*/docs/*|*/samples/*|*/examples/*|*/tests/*|*/archive/*) return 0 ;;
        */packages/*) return 0 ;;
        */output/*|*/preview/*|*/videos/*) return 0 ;;
    esac
    return 1
}

has_marker() {
    local file="$1"
    local marker="$2"
    head -n 20 "$file" 2>/dev/null | grep -qiF "$marker"
}

has_no_venv_marker() {
    head -n 10 "$1" 2>/dev/null | grep -qEi '^\s*#\s*no-venv\s*$'
}

is_python_shebang() {
    local first_line
    first_line=$(head -n 1 "$1" 2>/dev/null || true)
    [[ "$first_line" =~ ^#!.*python[0-9.]*([[:space:]]|$) || "$first_line" =~ ^#!.*env[[:space:]]+python[0-9.]*([[:space:]]|$) ]]
}

is_shell_shebang() {
    local first_line
    first_line=$(head -n 1 "$1" 2>/dev/null || true)
    [[ "$first_line" =~ ^#!.*(bash|sh)([[:space:]]|$) || "$first_line" =~ ^#!.*env[[:space:]]+(bash|sh)([[:space:]]|$) ]]
}

is_powershell_shebang() {
    local first_line
    first_line=$(head -n 1 "$1" 2>/dev/null || true)
    [[ "$first_line" =~ ^#!.*(pwsh|powershell)([[:space:]]|$) || "$1" == *.ps1 ]]
}

repo_root_for_file() {
    local dir
    dir=$(dirname "$(realpath_safe "$1")")
    while [[ "$dir" != "/" ]]; do
        if [[ -d "$dir/tools" && -d "$dir/packages" ]]; then
            echo "$dir"
            return 0
        fi
        dir=$(dirname "$dir")
    done
    return 1
}

find_project_python() {
    local dir
    dir=$(dirname "$(realpath_safe "$1")")
    while [[ "$dir" == "$SOURCE_DIR" || "$dir" == "$SOURCE_DIR"/* ]]; do
        if [[ -x "$dir/.venv/bin/python" ]]; then
            echo "$dir/.venv/bin/python"
            return 0
        fi
        if [[ -x "$dir/venv/bin/python" ]]; then
            echo "$dir/venv/bin/python"
            return 0
        fi
        [[ "$dir" == "/" ]] && break
        dir=$(dirname "$dir")
    done
    echo "/usr/bin/env python3"
}

command_name_for_file() {
    local file="$1"
    local explicit_name=""
    local base

explicit_name=$(head -n 20 "$file" 2>/dev/null | sed -nE 's/^[[:space:]]*(#|REM)[[:space:]]*scripts-toolbox:[[:space:]]*command=([A-Za-z0-9._-]+)[[:space:]]*$/\2/Ip' | head -n 1)
    if [[ -n "$explicit_name" ]]; then
        echo "$explicit_name"
        return 0
    fi

    base=$(basename "$file")
    case "$base" in
        *.py) echo "${base%.py}" ;;
        *.sh) echo "${base%.sh}" ;;
        *.ps1) echo "${base%.ps1}" ;;
        *.bat) echo "${base%.bat}" ;;
        *.cmd) echo "${base%.cmd}" ;;
        *) echo "$base" ;;
    esac
}

should_include_file() {
    local file="$1"
    local ext="${file##*.}"

    is_ignored_path "$file" && return 1
    has_marker "$file" "$TOOLBOX_NO_PATH_MARKER" && return 1

    case "$ext" in
        py) [[ $INCLUDE_PY -eq 1 ]] || return 1; is_python_shebang "$file" || return 1 ;;
        sh) [[ $INCLUDE_SH -eq 1 ]] || return 1; is_shell_shebang "$file" || return 1 ;;
        ps1) [[ $INCLUDE_PS1 -eq 1 ]] || return 1; is_powershell_shebang "$file" || return 1 ;;
        bat|cmd) [[ $INCLUDE_BAT -eq 1 ]] || return 1 ;;
        *) return 1 ;;
    esac

    if has_marker "$file" "$TOOLBOX_ENTRYPOINT_MARKER"; then
        return 0
    fi

    [[ $INCLUDE_UNMARKED -eq 1 ]]
}

collect_script_files() {
    find "$SOURCE_DIR" -type f \( -name '*.py' -o -name '*.sh' -o -name '*.ps1' -o -name '*.bat' -o -name '*.cmd' \) -print |
        while IFS= read -r file; do
            if should_include_file "$file"; then
                printf '%s\n' "$file"
            fi
        done
}

create_shell_wrapper() {
    local source_file="$1"
    local target_file="$2"
    local interpreter="$3"
    local repo_root=""

    repo_root=$(repo_root_for_file "$source_file" || true)
    rm -f "$target_file"

    {
        echo '#!/usr/bin/env bash'
        echo "$WRAPPER_MARKER"
        if [[ -n "$repo_root" && -d "$repo_root/packages/python" ]]; then
            printf "export PYTHONPATH=%q\${PYTHONPATH:+:\$PYTHONPATH}\n" "$repo_root/packages/python"
        fi
        if [[ "$interpreter" == "/usr/bin/env python3" ]]; then
            printf 'exec /usr/bin/env python3 %q "$@"\n' "$source_file"
        else
            printf 'exec %q %q "$@"\n' "$interpreter" "$source_file"
        fi
    } > "$target_file"

    chmod +x "$target_file"
}

create_symlink() {
    local source_file="$1"
    local target_file="$2"

    if [[ ! -L "$target_file" && "$(realpath_safe "$source_file")" == "$(realpath_safe "$target_file")" ]]; then
        echo "  ! skip: source and target are the same file"
        return 1
    fi

    rm -f "$target_file"
    ln -sf "$source_file" "$target_file"
    chmod +x "$source_file"
}

is_managed_wrapper() {
    [[ -f "$1" ]] && head -n 3 "$1" 2>/dev/null | grep -qF "$WRAPPER_MARKER"
}

cleanup_target_dir() {
    echo "Почиствам остарели команди в $TARGET_DIR..."
    [[ -d "$TARGET_DIR" ]] || return 0

    local item target
    for item in "$TARGET_DIR"/*; do
        [[ -e "$item" || -L "$item" ]] || continue
        if [[ -L "$item" && ! -e "$item" ]]; then
            echo "Премахвам счупен symlink: $item"
            [[ $DRYRUN -eq 0 ]] && rm -f "$item"
            continue
        fi
        if is_managed_wrapper "$item"; then
            target=$(grep '^exec ' "$item" | sed -E 's/.* ([^ ]+) "\$@"/\1/' | tr -d '"' || true)
            if [[ -n "$target" && "$target" == /* && ! -e "$target" ]]; then
                echo "Премахвам wrapper към липсващ файл: $item"
                [[ $DRYRUN -eq 0 ]] && rm -f "$item"
            fi
        fi
    done
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help) show_help; exit 0 ;;
        -n|--dry-run) DRYRUN=1 ;;
        -c|--clean) CLEAN=1 ;;
        -t|--target) shift; TARGET_DIR="${1:-}" ;;
        -s|--source) shift; SOURCE_DIR="${1:-}" ;;
        -p|--python) INCLUDE_PY=1 ;;
        -b|--bash) INCLUDE_SH=1 ;;
        -w|--powershell) INCLUDE_PS1=1 ;;
        -B|--bat) INCLUDE_BAT=1 ;;
        -a|--all) INCLUDE_ALL=1 ;;
        -u|--include-unmarked) INCLUDE_UNMARKED=1 ;;
        --*) fail "непозната опция: $1" ;;
        *) SOURCE_DIR="$1" ;;
    esac
    shift || true
done

if [[ $INCLUDE_ALL -eq 1 ]]; then
    INCLUDE_PY=1
    INCLUDE_SH=1
    INCLUDE_PS1=1
    INCLUDE_BAT=1
fi

TARGET_DIR=$(realpath_safe "$TARGET_DIR")
if [[ $DRYRUN -eq 0 ]]; then
    mkdir -p "$TARGET_DIR"
fi

if [[ $CLEAN -eq 1 ]]; then
    cleanup_target_dir
    exit 0
fi

[[ -n "$SOURCE_DIR" ]] || { show_help; exit 1; }
[[ -d "$SOURCE_DIR" ]] || fail "source не е директория: $SOURCE_DIR"
SOURCE_DIR=$(realpath_safe "$SOURCE_DIR")

printf 'Source: %s\n' "$SOURCE_DIR"
printf 'Target: %s\n' "$TARGET_DIR"
mode_suffix=""
if [[ $INCLUDE_UNMARKED -eq 1 ]]; then
    mode_suffix=" + unmarked shebang скриптове"
fi
printf 'Режим:  marked entrypoints%s\n\n' "$mode_suffix"

declare -A SEEN_COMMANDS=()

while IFS= read -r file; do
    [[ -n "$file" ]] || continue
    abs_file=$(realpath_safe "$file")
    cmd_name=$(command_name_for_file "$abs_file")
    target_file="$TARGET_DIR/$cmd_name"
    ext="${abs_file##*.}"

    if [[ -n "${SEEN_COMMANDS[$cmd_name]:-}" ]]; then
        echo "! конфликт: командата '$cmd_name' вече сочи към ${SEEN_COMMANDS[$cmd_name]}" >&2
        echo "! пропуснато: $abs_file" >&2
        continue
    fi
    SEEN_COMMANDS[$cmd_name]="$abs_file"

    echo "-> $abs_file"
    echo "   команда: $target_file"

    if [[ $DRYRUN -eq 1 ]]; then
        continue
    fi

    case "$ext" in
        py)
            if has_no_venv_marker "$abs_file"; then
                create_shell_wrapper "$abs_file" "$target_file" "/usr/bin/env python3"
            else
                create_shell_wrapper "$abs_file" "$target_file" "$(find_project_python "$abs_file")"
            fi
            ;;
        sh)
            create_symlink "$abs_file" "$target_file"
            ;;
        ps1)
            create_shell_wrapper "$abs_file" "$target_file" "/usr/bin/env pwsh"
            ;;
        bat|cmd)
            create_symlink "$abs_file" "$target_file"
            ;;
    esac
done < <(collect_script_files | sort -fu)

echo
echo "Готово. Увери се, че $TARGET_DIR е в PATH."
