<#
.SYNOPSIS
    Инсталира scripts-toolbox командите в Windows чрез .cmd wrapper-и.

.DESCRIPTION
    Сканира repo-то за файлове с marker "scripts-toolbox: entrypoint" и създава
    command wrapper-и в target директория, например $HOME\bin. Така не се добавя
    цялото repo дърво към PATH и не са нужни права за symlink-и.
#>

[CmdletBinding()]
param(
    [string]$Source = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path,
    [string]$Target = (Join-Path $HOME "bin"),
    [switch]$Python,
    [switch]$PowerShell,
    [switch]$Batch,
    [switch]$All,
    [switch]$IncludeUnmarked,
    [switch]$DryRun,
    [switch]$Clean,
    [switch]$Help
)

$EntryPointMarker = "scripts-toolbox: entrypoint"
$NoPathMarker = "scripts-toolbox: no-path"
$WrapperMarker = "generated by scripts-toolbox Install-ToPath.ps1"

if ($Help) {
    Get-Help $PSCommandPath -Detailed
    exit 0
}

function Write-Info($Message) {
    Write-Host $Message
}

function Test-IgnoredPath([string]$Path) {
    $normalized = $Path -replace '\\', '/'
    return ($normalized -match '/(\.git|\.idea|\.vscode|__pycache__|\.pytest_cache|\.venv|venv|env|node_modules)/' -or
            $normalized -match '/(bootstrap|docs|samples|examples|tests|archive|packages)/' -or
            $normalized -match '/(output|preview|videos)/')
}

function Get-Header([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return @() }
    return Get-Content -LiteralPath $Path -TotalCount 20 -ErrorAction SilentlyContinue
}

function Test-HasMarker([string]$Path, [string]$Marker) {
    return ((Get-Header $Path) -match [regex]::Escape($Marker)).Count -gt 0
}

function Get-CommandName([string]$Path) {
    $header = Get-Header $Path
    foreach ($line in $header) {
        if ($line -match '^\s*(#|REM)\s*scripts-toolbox:\s*command=([A-Za-z0-9._-]+)\s*$') {
            return $Matches[2]
        }
    }

    $name = [IO.Path]::GetFileNameWithoutExtension($Path)
    return $name
}

function Test-PythonShebang([string]$Path) {
    $first = (Get-Content -LiteralPath $Path -TotalCount 1 -ErrorAction SilentlyContinue)
    return $first -match '^#!.*(python|env\s+python)'
}

function Test-PowerShellScript([string]$Path) {
    return [IO.Path]::GetExtension($Path).ToLowerInvariant() -eq '.ps1'
}

function Test-BatchScript([string]$Path) {
    $ext = [IO.Path]::GetExtension($Path).ToLowerInvariant()
    return $ext -eq '.bat' -or $ext -eq '.cmd'
}

function Test-IncludedFile([string]$Path) {
    if (Test-IgnoredPath $Path) { return $false }
    if (Test-HasMarker $Path $NoPathMarker) { return $false }

    $ext = [IO.Path]::GetExtension($Path).ToLowerInvariant()
    switch ($ext) {
        '.py'  { if (-not $Python) { return $false }; if (-not (Test-PythonShebang $Path)) { return $false } }
        '.ps1' { if (-not $PowerShell) { return $false }; if (-not (Test-PowerShellScript $Path)) { return $false } }
        '.bat' { if (-not $Batch) { return $false } }
        '.cmd' { if (-not $Batch) { return $false } }
        default { return $false }
    }

    if (Test-HasMarker $Path $EntryPointMarker) { return $true }
    return [bool]$IncludeUnmarked
}

function New-CmdWrapper([string]$ScriptPath, [string]$CommandPath) {
    $ext = [IO.Path]::GetExtension($ScriptPath).ToLowerInvariant()
    $content = @("@echo off", "REM $WrapperMarker")

    if ($ext -eq '.py') {
        $content += "py `"$ScriptPath`" %*"
    } elseif ($ext -eq '.ps1') {
        $content += "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$ScriptPath`" %*"
    } else {
        $content += "call `"$ScriptPath`" %*"
    }

    Set-Content -LiteralPath $CommandPath -Value $content -Encoding ASCII
}

function Invoke-Clean([string]$TargetDir) {
    if (-not (Test-Path -LiteralPath $TargetDir -PathType Container)) { return }
    Get-ChildItem -LiteralPath $TargetDir -Filter '*.cmd' | ForEach-Object {
        $header = Get-Content -LiteralPath $_.FullName -TotalCount 3 -ErrorAction SilentlyContinue
        if (($header -match [regex]::Escape($WrapperMarker)).Count -gt 0) {
            Write-Info "Премахвам managed wrapper: $($_.FullName)"
            if (-not $DryRun) { Remove-Item -LiteralPath $_.FullName -Force }
        }
    }
}

if ($All) {
    $Python = $true
    $PowerShell = $true
    $Batch = $true
}

if (-not $Python -and -not $PowerShell -and -not $Batch) {
    $PowerShell = $true
    $Batch = $true
}

$Source = (Resolve-Path -LiteralPath $Source).Path
$Target = [IO.Path]::GetFullPath($Target)

if ($Clean) {
    Invoke-Clean $Target
    exit 0
}

if (-not $DryRun -and -not (Test-Path -LiteralPath $Target -PathType Container)) {
    New-Item -ItemType Directory -Path $Target | Out-Null
}

Write-Info "Source: $Source"
Write-Info "Target: $Target"
Write-Info "Режим: marked entrypoints$(if ($IncludeUnmarked) { ' + unmarked скриптове' } else { '' })"
Write-Info ""

$seen = @{}
Get-ChildItem -LiteralPath $Source -Recurse -File -Include *.py,*.ps1,*.bat,*.cmd |
    Where-Object { Test-IncludedFile $_.FullName } |
    Sort-Object FullName |
    ForEach-Object {
        $cmdName = Get-CommandName $_.FullName
        $targetFile = Join-Path $Target ($cmdName + '.cmd')

        if ($seen.ContainsKey($cmdName)) {
            Write-Warning "Конфликт: командата '$cmdName' вече сочи към $($seen[$cmdName]); пропуснато $($_.FullName)"
            return
        }
        $seen[$cmdName] = $_.FullName

        Write-Info "-> $($_.FullName)"
        Write-Info "   команда: $targetFile"
        if (-not $DryRun) {
            New-CmdWrapper $_.FullName $targetFile
        }
    }

Write-Info ""
Write-Info "Готово. Увери се, че $Target е в PATH."
